### ISSUE TITLE
Is there any migration feature project in plan?

### ISSUE THREAD

**Issue by sicaboy** [FahimF/SQLiteDB#36]
Is there any migration feature similar to the following project in plan?

https://github.com/garriguv/SQLiteMigrationManager.swift

**Comment by FahimF** [comment]
No, since that would not make sense for SQLiteDB since the DB does not contain any schema information. You can write your own management code however using the versioning functionality added via the SQLiteDB "set" command and checking the DB at the launch of your app to see if the version number has changed.
