### ISSUE TITLE
how insert data TRANSACTION

### ISSUE THREAD

**Issue by kavoskhajavi** [FahimF/SQLiteDB#41]
how 300 record insert to sqlite 

for item in data {

 let resultQ = self.db.execute(sql: "INSERT INTO tabel  (\(key))VALUES (\(value))")
}

**Comment by FahimF** [comment]
There is no explicit support for TRANSACTION in SQLiteDB where you can rollback a set of transactions via the SQLiteDB framework itself. However, you might be able to do this via code by executing "BEGIN TRANSACTION"  as an SQL command and then running multiple INSERT statements followed by a COMMIT. I am not absolutely sure if this would work or not since I have not tried this out myself.
