### ISSUE TITLE
WatchOS Compatibility

### ISSUE THREAD

**Issue by jmanoel** [FahimF/SQLiteDB#43]
When I tried to compile on WatchOS shows that AppKit doesn't exists. What we need to do to compile on WatchOs 3 ?

**Comment by FahimF** [comment]
The AppKit doesn't exist error was probably because of a compiler directive to detect the OS which falls through to macOS by default. You would need to look at the compiler directives and add a watchOS directive if you want to do it yourself. Not quite sure if everything would work correctly on watchOS since I had not tested for this. So you'd need to do that at your end as well.

**Comment by jmanoel** [comment]
Hello. Your code worked fine. Just need to check the os if is watchOS and then import UIKit too on both SQLiteDB and SQTable 

#if os(watchOS)
import UIKit
#else 
import AppKit


Thank you

**Comment by FahimF** [comment]
Great :) Good to do know that the code works fine under watchOS too. Thanks for letting me know!
