### ISSUE TITLE
Db versioning help

### ISSUE THREAD

**Issue by ConorBeckett** [FahimF/SQLiteDB#47]
Hi Fahim,

First off, huge thanks for a great library!

My scenario is that I have an onboard db that is copied to the device as per your library.
All the sql query functions work perfectly.
I run the db.getDBVersion() function and it correctly pulls in the user_pragma version.

Now I run into a the problems.

When I update my .db file and add the new .db to the xcode project and install the new version of the app on my device the db.getDBVersion() comes back with the original version that is copied to the device.

Was just wondering if you had any ideas on identifying the new version and overwriting the already copied version / or have i missed something in your library.

Hope this makes sense and hope to hear from you.

Cheers

**Comment by FahimF** [comment]
SQLiteDB itself does not provide anything to handle the migration from the old DB to the new one since you might have existing data on the old DB that you don't want overwritten. Instead, what I do to handle version changes for existing databases is to check the loaded DB version against a hard-coded version in my app code. If the version is different, I update the DB based on the old version till the DB is up-to-date and then update the DB version on the DB at that point.

Hope that helps :)
