### ISSUE TITLE
Support for Int64

### ISSUE THREAD

**Issue by DavidTomic** [FahimF/SQLiteDB#48]
Hi,

It's look like Int64 is not supported in this database implementation ?

**Comment by icerao** [comment]
I have the same problem

**Comment by vas7n** [comment]
I have the same problem

**Comment by FahimF** [comment]
I was waiting to find some time to look into all the ramifications of having Int64 support as a separate type vs. making Int64 the standard type since Int in Swift would be either 64-bit or 32-bit depending on the platform.  However, since the latest macOS and iOS is both 64-bit, I decided to simply go ahead and make the change. The latest code should simply support Int64 out of the box.
