### ISSUE TITLE
Error handling while not initializing database

### ISSUE THREAD

**Issue by Rickrk** [FahimF/SQLiteDB#54]
If I didn't call OpenDB() before and want to execute a query, my app fails and it says "assertion failed: Database has not been opened! Use the openDB() method before any DB queries". 
I used do-catch and inside "do" I call db.execute(sql) but it failed again.
How can I use d-catch to handle errors?

**Comment by FahimF** [comment]
You have to call openDB() before you can execute queries. That's why the assertion is there. Why would you want to run queries without opening the database?

**Comment by Rickrk** [comment]
Yes I know. I want to handle some other errors that may happen. It's not important what errors will happen, I just want to prevent crashing my app due to errors may happen. I tried to use "do-catch" and calling "execute" function with "try", but the problem still exists.

**Comment by FahimF** [comment]
An assert is a debug only crash - it will not happen at runtime. It is there to let developers know that something was not set up correctly when you write code and first run it. You can catch errors via try - catch only if the code throws an exception. So you will not be able to catch the openDB() error that way since SQLiteDB does not do a throw at that point.

So the question is, are you asking that SQLiteDB throw exceptions for specific issues? If so, what are the issues for which you want SQLiteDB to throw exceptions? I had not added throwing exceptions since for my own use, exceptions were superfluous.

**Comment by Rickrk** [comment]
Thank you. It seems this is my lack of knowledge about assert. Sorry.
No there is not any specific issue and I don't want to use throwing exceptions. That's just for assurance to prevent crashing the app.
