### ISSUE TITLE
table names

### ISSUE THREAD

**Issue by effcore** [FahimF/SQLiteDB#56]
1) table names should not be handled case sensitive, since they are forced to lowercase. so if there's an upper-case character, the select-statement from sqlite_master will fail because the operator '=' is used instead of 'like' or lower(/(tablename)) = lower(name).

2) currently there is a suffix-replacement. table-names ending with "y" are replaced with "ies" and all other table-names are extended with "s". that's only useful for the english language and should be documented. of course it wasn't difficult to replace them, just wondered... :-)

e.g.
original tablename: tblPerson
variable: tnm = tblpersons
statement: SELECT * FROM sqlite_master WHERE type = 'table' AND name = 'tblpersons'; = 0 results

**Comment by FahimF** [comment]
Thanks for reporting these :) I've fixed #1 and it should appear in the next code update though that wont' be for a while since I'm in the middle of adding some major functionality.

I'm afraid that #2 is a matter of taste. I agree that it only works if you're using English but since it's documented (and you can always change the code if you don't like the behaviour), I'm not planning to change it.
