### ISSUE TITLE
string primaryKey

### ISSUE THREAD

**Issue by ralcr** [FahimF/SQLiteDB#59]
Hi, in the save method i noticed that the primary key is not unwrapped, so the query fails for optional string key.

func save() -> Int {
		let db = SQLiteDB.shared!
		let key = primaryKey()
		let data = values()
		var insert = true
		if let rid = data[key] {
			var val = "\(rid)"
			if let _rid = rid as? String {
				val = "'\(_rid)'"
			}

**Comment by FahimF** [comment]
Why would you have an optional as the primary key? The whole idea of a primary key is for it to be there, right? If you have an optional, you could have multiple records with no primary key. Or am I missing a possible scenario where this actually might be necessary/useful?

**Comment by ralcr** [comment]
I think you're right, seems more like a mistake in my code because i didn't thought of it, i'm doing a conversion between a model in the app with the model in the database, and the one in database has everything optional. The problem is that it happened without me knowing and i think is still a better check. Maybe a warning could be implemented.

**Comment by FahimF** [comment]
I'll have to think about this a bit to consider all the ramifications. For example, it is customary for there not to be a primary key if you have an auto-incremented column. Plus, you will not even get into the bit about the optional string key if there is no key since the `if let rid = data[key]` condition will fail. But at that point, I can't assume that there has to be a primary key since the key could be an auto-increment column.

Does that make sense?

I understand your intent here and I guess the solution would be to check if the primary key is string and then throw a warning if there is no primary key but I don't know if the additional processing required for that check is justifiable for most use-case scenarios. So need to think about it ...
